
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalyzerJavascript;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 22;
  public static final int MENOR = 20;
  public static final int ELSE = 25;
  public static final int CLASS = 6;
  public static final int CADCOM = 16;
  public static final int OR = 23;
  public static final int IGUAL = 15;
  public static final int DECIMAL = 9;
  public static final int NOT = 24;
  public static final int LLARIGHT = 3;
  public static final int IF = 18;
  public static final int CARACTERESVARIABLES = 7;
  public static final int LLALEFT = 2;
  public static final int COMA = 10;
  public static final int MAYOR = 21;
  public static final int EOF = 0;
  public static final int NUMBER = 8;
  public static final int CADCOMSIM = 17;
  public static final int PARRIGHT = 5;
  public static final int CONST = 14;
  public static final int error = 1;
  public static final int LET = 13;
  public static final int PARLEFT = 4;
  public static final int PCOMA = 11;
  public static final int ADMIR = 19;
  public static final int VAR = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLALEFT",
  "LLARIGHT",
  "PARLEFT",
  "PARRIGHT",
  "CLASS",
  "CARACTERESVARIABLES",
  "NUMBER",
  "DECIMAL",
  "COMA",
  "PCOMA",
  "VAR",
  "LET",
  "CONST",
  "IGUAL",
  "CADCOM",
  "CADCOMSIM",
  "IF",
  "ADMIR",
  "MENOR",
  "MAYOR",
  "AND",
  "OR",
  "NOT",
  "ELSE"
  };
}

