
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 7;
  public static final int LLALEFT = 4;
  public static final int DECIMAL = 11;
  public static final int PCOMA = 13;
  public static final int UMINUS = 12;
  public static final int PARLEFT = 2;
  public static final int NUMBER = 10;
  public static final int RGENERARREPORTEESTADISTICO = 14;
  public static final int PARRIGHT = 3;
  public static final int EOF = 0;
  public static final int ADD = 6;
  public static final int DIV = 9;
  public static final int error = 1;
  public static final int TIMES = 8;
  public static final int LLARIGHT = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARLEFT",
  "PARRIGHT",
  "LLALEFT",
  "LLARIGHT",
  "ADD",
  "MINUS",
  "TIMES",
  "DIV",
  "NUMBER",
  "DECIMAL",
  "UMINUS",
  "PCOMA",
  "RGENERARREPORTEESTADISTICO"
  };
}

