
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 28;
  public static final int LLALEFT = 4;
  public static final int CARACTERESVARIABLES = 19;
  public static final int UMINUS = 14;
  public static final int GRAFICAPIE = 33;
  public static final int DOUBLE = 22;
  public static final int MINUS = 9;
  public static final int TITULOY = 30;
  public static final int TITULOX = 31;
  public static final int EJEX = 29;
  public static final int IGUAL = 20;
  public static final int PUNTAJEGENERAL = 36;
  public static final int ARCHIVO = 35;
  public static final int TITULO = 27;
  public static final int DIV = 11;
  public static final int COLEFT = 6;
  public static final int DEFINIRGLOBALES = 23;
  public static final int RGENERARREPORTEESTADISTICO = 16;
  public static final int EOF = 0;
  public static final int DECIMAL = 13;
  public static final int VALORES = 32;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int ADD = 8;
  public static final int GRAFICALINEAS = 34;
  public static final int NUMBER = 12;
  public static final int LLARIGHT = 5;
  public static final int CADENACOMILLAS = 24;
  public static final int PCOMA = 15;
  public static final int PARRIGHT = 3;
  public static final int CADENACOMILLASSIMPLE = 25;
  public static final int TIMES = 10;
  public static final int COMPARE = 17;
  public static final int PARLEFT = 2;
  public static final int GRAFICADEBARRAS = 26;
  public static final int CORIGHT = 7;
  public static final int STRING = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARLEFT",
  "PARRIGHT",
  "LLALEFT",
  "LLARIGHT",
  "COLEFT",
  "CORIGHT",
  "ADD",
  "MINUS",
  "TIMES",
  "DIV",
  "NUMBER",
  "DECIMAL",
  "UMINUS",
  "PCOMA",
  "RGENERARREPORTEESTADISTICO",
  "COMPARE",
  "COMA",
  "CARACTERESVARIABLES",
  "IGUAL",
  "STRING",
  "DOUBLE",
  "DEFINIRGLOBALES",
  "CADENACOMILLAS",
  "CADENACOMILLASSIMPLE",
  "GRAFICADEBARRAS",
  "TITULO",
  "DOSPUNTOS",
  "EJEX",
  "TITULOY",
  "TITULOX",
  "VALORES",
  "GRAFICAPIE",
  "GRAFICALINEAS",
  "ARCHIVO",
  "PUNTAJEGENERAL"
  };
}

